"""resume variants and render artifacts

Revision ID: ade973186357
Revises: 2a43da6dadee
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ade973186357"
down_revision: str | None = "2a43da6dadee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume_variants",
        sa.Column("current_revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "current_revision > 0", name=op.f("ck_resume_variants_positive_revision")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_variants")),
    )
    op.create_table(
        "resume_variant_revisions",
        sa.Column("resume_variant_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_revision_id", sa.Uuid(), nullable=True),
        sa.Column("document", postgresql.JSONB(), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "revision > 0", name=op.f("ck_resume_variant_revisions_positive_revision")
        ),
        sa.ForeignKeyConstraint(
            ["job_revision_id"],
            ["job_revisions.id"],
            name=op.f("fk_resume_variant_revisions_job_revision_id_job_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["personal_profiles.id"],
            name=op.f("fk_resume_variant_revisions_profile_id_personal_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resume_variant_id"],
            ["resume_variants.id"],
            name=op.f("fk_resume_variant_revisions_resume_variant_id_resume_variants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_variant_revisions")),
        sa.UniqueConstraint(
            "resume_variant_id",
            "revision",
            name=op.f("uq_resume_variant_revisions_resume_variant_id"),
        ),
    )
    op.create_table(
        "render_artifacts",
        sa.Column("resume_variant_id", sa.Uuid(), nullable=False),
        sa.Column("resume_variant_revision", sa.Integer(), nullable=False),
        sa.Column("artifact_ref", sa.Uuid(), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("report", postgresql.JSONB(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(report->>'render_status' = 'accepted') = (artifact_ref IS NOT NULL)",
            name=op.f("ck_render_artifacts_accepted_file"),
        ),
        sa.CheckConstraint(
            "report->>'render_status' != 'accepted' OR "
            "(report->>'validation_status' = 'passed' AND report->>'page_count' = '1')",
            name=op.f("ck_render_artifacts_accepted_validation"),
        ),
        sa.CheckConstraint(
            "(artifact_ref IS NULL) = (file_hash IS NULL)",
            name=op.f("ck_render_artifacts_artifact_hash_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["resume_variant_id", "resume_variant_revision"],
            ["resume_variant_revisions.resume_variant_id", "resume_variant_revisions.revision"],
            name=op.f("fk_render_artifacts_resume_variant_id_resume_variant_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_render_artifacts")),
        sa.UniqueConstraint("artifact_ref", name=op.f("uq_render_artifacts_artifact_ref")),
    )
    op.execute("""
        CREATE FUNCTION prevent_resume_revision_update() RETURNS trigger AS $$
        BEGIN RAISE EXCEPTION 'resume_revision_immutable'; END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER resume_revision_immutable BEFORE UPDATE ON resume_variant_revisions
        FOR EACH ROW EXECUTE FUNCTION prevent_resume_revision_update()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("render_artifacts")
    op.drop_table("resume_variant_revisions")
    op.execute("DROP FUNCTION prevent_resume_revision_update()")
    op.drop_table("resume_variants")
    # ### end Alembic commands ###
